# Generated by Django 4.0.4 on 2022-07-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('credit', models.IntegerField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('theory', models.IntegerField(max_length=100)),
                ('tutorial', models.IntegerField(max_length=100)),
                ('lab', models.IntegerField(max_length=100)),
                ('lab_name', models.CharField(max_length=100)),
            ],
        ),
    ]
